spring:
  datasource:
    url: jdbc:h2:~/local
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: DEBUG

--- # default
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:~/local
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

--- # test
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:~/test
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop